// This file is automatically generated. Do not edit it directly.
// (Hand-edited to fail safe: the client is only constructed when the public
// environment variables are present and well-formed.)
import { createClient, type SupabaseClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

/** Returns a trimmed http(s) URL string, or null when missing/malformed. */
function parseSupabaseUrl(raw: unknown): string | null {
  if (typeof raw !== 'string') return null;
  const trimmed = raw.trim();
  if (!trimmed) return null;
  try {
    const parsed = new URL(trimmed);
    if (parsed.protocol !== 'https:' && parsed.protocol !== 'http:') return null;
    return trimmed;
  } catch {
    return null;
  }
}

const supabaseUrl = parseSupabaseUrl(SUPABASE_URL);
const supabaseKey =
  typeof SUPABASE_PUBLISHABLE_KEY === 'string' && SUPABASE_PUBLISHABLE_KEY.trim().length > 0
    ? SUPABASE_PUBLISHABLE_KEY
    : null;

/**
 * True only when both the public URL and publishable key are present and
 * well-formed. Consumers should check this (or the `supabase` null value)
 * before making any request, so a missing configuration degrades gracefully
 * instead of crashing the SPA at module load.
 */
export const isSupabaseConfigured = supabaseUrl !== null && supabaseKey !== null;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
//
// `supabase` is null when configuration is missing. Guard with
// `isSupabaseConfigured` (or a null check) before use.
export const supabase: SupabaseClient<Database> | null =
  supabaseUrl !== null && supabaseKey !== null
    ? createClient<Database>(supabaseUrl, supabaseKey, {
        auth: {
          storage: localStorage,
          persistSession: true,
          autoRefreshToken: true,
        },
      })
    : null;
